# -*- mode: python ; coding: utf-8 -*-
"""测试包：生成 tset.exe，不覆盖 MediaScraper.exe。"""

import os

block_cipher = None
ROOT = os.path.abspath(".")

hiddenimports = [
    "providers",
    "providers.base",
    "providers.registry",
    "providers.aggregator",
    "providers.http_client",
    "providers.javdb",
    "providers.javbus",
    "providers.javdatabase",
    "providers.javlibrary",
    "providers.javinfo",
    "providers.dmm",
    "providers.tmdb",
    "providers.mock",
    "providers.choices",
    "providers.net",
    "providers.page_parse",
    "providers.confidence",
    "providers.simple",
    "providers.r18dev",
    "providers.jav321",
    "providers.libredmm",
    "providers.avsox",
    "providers.javmenu",
    "providers.javtxt",
    "providers.javstore",
    "providers.fc2",
    "providers.heyzo",
    "providers.caribbeancom",
    "providers.tokyohot",
    "providers.maker_json",
    "providers.faleno",
    "providers.aventertainments",
    "core",
    "core.config",
    "core.app_paths",
    "core.http_sessions",
    "core.page_cache",
    "core.logging_setup",
    "core.orchestrator",
    "core.pipeline_apply",
    "core.pipeline_persist",
    "core.parser",
    "core.scanner",
    "core.models",
    "core.progress",
    "core.chinese_utils",
    "core.proxy",
    "core.fc2_auth",
    "aiohttp_socks",
    "aiohttp_socks.connector",
    "PIL",
    "PIL.Image",
    "PIL.ImageDraw",
    "PIL.ImageFile",
    "PIL.JpegImagePlugin",
    "PIL.PngImagePlugin",
    "PIL.GifImagePlugin",
    "PIL.WebPImagePlugin",
    "metadata",
    "metadata.nfo",
    "metadata.json_writer",
    "metadata.image",
    "rename",
    "rename.renamer",
    "rename.sanitizer",
    "gui",
    "gui.main_window",
    "gui.worker",
    "gui.settings_dialog",
    "gui.proxy_test_worker",
    "gui.fc2_login_dialog",
    "gui.theme",
    "gui.row_widgets",
]

datas = [
    ("config.example.yaml", "."),
    ("assets/app.ico", "assets"),
    ("assets/dark.qss", "assets"),
    ("assets/light.qss", "assets"),
]

a = Analysis(
    ["app_gui.py"],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "pydoc"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="tset",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/app.ico",
    version="version_info.txt",
)
